version: '3'
services:
  elasticsearch:
    container_name: elasticsearch
    image: docker.elastic.co/elasticsearch/elasticsearch:7.16.1
    environment:
      - discovery.type=single-node
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms1g -Xmx1g"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      # local ES data directory
      - ./esdata:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
      - 9300:9300
  #diskover python app
  diskover:
    image: python:3.7-buster
    container_name: diskover
    build:
      context: ./diskover
      dockerfile: diskover.dockerfile
    working_dir: /app/diskover
    environment:
      # diskoverd task worker (Essential + versions only)
      -  DISKOVERD_WORKERNAME=docker-worker
    volumes:
      - ./diskover:/app/diskover
      # diskover config files
      - ./diskover/configs:/root/.config
      # mount points for crawling
      - /mnt/:/data
  # diskover-web php app
  diskover-web:
    image: php:7.4-fpm
    container_name: diskover-web-app
    build:
      context: ./diskover-web
      dockerfile: diskover-web.dockerfile
    working_dir: /var/www
    volumes:
      - ./diskover-web:/var/www
  # Nginx web server
  nginx:
    image: nginx:1.21
    container_name: diskover-web-nginx
    working_dir: /var/www
    labels:
      traefik.enable: 'true'
      traefik.port: '8000'
      traefik.frontend.auth.forward.address: ''
      traefik.frontend.rule: 'Host:diskover.pi.co.nz'
      traefik.frontend.headers.SSLHost: 'pi.co.nz'
      traefik.frontend.headers.SSLRedirect: 'true'
      traefik.frontend.headers.STSIncludeSubdomains: 'true'
      traefik.frontend.headers.STSPreload: 'true'
      traefik.frontend.headers.STSSeconds: '315360000'
      traefik.frontend.headers.browserXSSFilter: 'true'
      traefik.frontend.headers.contentTypeNosniff: 'true'
      traefik.frontend.headers.customResponseHeaders: 'X-Robots-Tag:noindex,nofollow,nosnippet,noarchive,notranslate,noimageindex'
      traefik.frontend.headers.forceSTSHeader: 'true'
    networks:
      - plexguide
    volumes:
      - ./diskover-web/diskover-web.conf:/etc/nginx/conf.d/diskover-web.conf
      - ./diskover-web:/var/www
    ports:
      - 8000:8000
